# Data Manipulation

In [1]:
import torch

In [2]:
x = torch.arange(12)

In [3]:
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
x.shape

torch.Size([12])

In [5]:
x.numel()

12

In [6]:
X = x.reshape(3, 4)

In [7]:
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [8]:
X.shape

torch.Size([3, 4])

In [9]:
X.numel()

12

In [10]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

## elementwise computations

In [11]:
x = torch.tensor([1, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3,  4,  6, 10]),
 tensor([-1,  0,  2,  6]),
 tensor([ 2,  4,  8, 16]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1,  4, 16, 64]))

In [12]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

## concatenate

In [13]:
x = torch.arange(12, dtype=torch.float32).reshape(3, 4)
y = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
z_1 = torch.cat((x, y), dim=0)
z_2 = torch.cat((x, y), dim=1)

In [14]:
z_1, z_2

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

## binary tensor

In [15]:
x == y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [16]:
b_tensor = x == y

In [17]:
b_tensor.sum()

tensor(2)

## broadcasting mechanism 

In [18]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

## indexing and slicing 

In [19]:
x, x[-1], x[1: 3]

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [20]:
x[0: 2, :] = 12

In [21]:
x

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [22]:
before = id(y)

In [23]:
before

140465457426080

In [24]:
y = y + x
id(y) == before

False

In [25]:
y

tensor([[14., 13., 16., 15.],
        [13., 14., 15., 16.],
        [12., 12., 12., 12.]])

In [26]:
before = id(x)
x = x + y
before == id(x)

False

In [27]:
before = id(x)
x += y
before == id(x)

True

In [28]:
x, y

(tensor([[40., 38., 44., 42.],
         [38., 40., 42., 44.],
         [32., 33., 34., 35.]]),
 tensor([[14., 13., 16., 15.],
         [13., 14., 15., 16.],
         [12., 12., 12., 12.]]))

In [29]:
x > y

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [30]:
x = torch.arange(12).reshape((2, 3, 2))
x

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]]])

In [31]:
y = torch.arange(6).reshape((2, 3, 1))
y

tensor([[[0],
         [1],
         [2]],

        [[3],
         [4],
         [5]]])

In [32]:
x + y

tensor([[[ 0,  1],
         [ 3,  4],
         [ 6,  7]],

        [[ 9, 10],
         [12, 13],
         [15, 16]]])

# Data Preprocessing

In [33]:
import pandas as pd

In [34]:
import os
os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')  # Column names
    f.write('NA,Pave,127500\n')  # Each row represents a data example
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [35]:
data = pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


In [36]:
inputs, outputs = data.iloc[:, 0: 2], data.iloc[:, 2]
inputs = inputs.fillna(inputs.mean())
print(inputs)

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


In [37]:
inputs = pd.get_dummies(inputs, dummy_na=True)
print(inputs)

   NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1


In [38]:
X, y = torch.tensor(inputs.values), torch.tensor(outputs.values)
X, y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000]))

# Linear Algebra

In [39]:
len(X)

4

In [40]:
X.shape

torch.Size([4, 3])

In [41]:
A = torch.arange(20).reshape((5, 4))

In [42]:
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [43]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

# Tensor

In [44]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)

In [45]:
id(A)

140465457443040

In [46]:
B = A
id(B)

140465457443040

In [47]:
B.T

tensor([[ 0.,  4.,  8., 12., 16.],
        [ 1.,  5.,  9., 13., 17.],
        [ 2.,  6., 10., 14., 18.],
        [ 3.,  7., 11., 15., 19.]])

In [48]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [49]:
B = A.clone()
A, A+B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [50]:
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [51]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

In [52]:
A_sum_axis0 = A.sum(axis=0)
A, A_sum_axis0, A_sum_axis0.shape

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([40., 45., 50., 55.]),
 torch.Size([4]))

In [53]:
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1, A_sum_axis1.shape

(tensor([ 6., 22., 38., 54., 70.]), torch.Size([5]))

## L2 Norm

In [54]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

## L1 Norm

In [55]:
torch.abs(u).sum()

tensor(7.)

# Derivative

In [56]:
import numpy as np

In [57]:
from IPython import display
from d2l import torch as d2l

In [58]:
def f(x):
    return 3 * x ** 2 - 4 * x

In [59]:
def numerical_lim(f, x, h):
    return (f(x + h) - f(x)) / h

In [60]:
h = 0.1

In [61]:
for i in range(5):
    print(f'h={h:.5f}, numerical limit={numerical_lim(f, 1, h):.5f}')
    h *= 0.1

h=0.10000, numerical limit=2.30000
h=0.01000, numerical limit=2.03000
h=0.00100, numerical limit=2.00300
h=0.00010, numerical limit=2.00030
h=0.00001, numerical limit=2.00003


In [62]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [63]:
help(torch.arange)

Help on built-in function arange:

arange(...)
    arange(start=0, end, step=1, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) -> Tensor
    
    Returns a 1-D tensor of size :math:`\left\lceil \frac{\text{end} - \text{start}}{\text{step}} \right\rceil`
    with values from the interval ``[start, end)`` taken with common difference
    :attr:`step` beginning from `start`.
    
    Note that non-integer :attr:`step` is subject to floating point rounding errors when
    comparing against :attr:`end`; to avoid inconsistency, we advise adding a small epsilon to :attr:`end`
    in such cases.
    
    .. math::
        \text{out}_{{i+1}} = \text{out}_{i} + \text{step}
    
    Args:
        start (Number): the starting value for the set of points. Default: ``0``.
        end (Number): the ending value for the set of points
        step (Number): the gap between each pair of adjacent points. Default: ``1``.
    
    Keyword args:
        out (Tensor, optiona

In [64]:
x = torch.arange(4.0, requires_grad=True)

In [65]:
x.grad

In [66]:
print(x.grad)

None


In [67]:
y = 2 * torch.dot(x, x)

In [68]:
y

tensor(28., grad_fn=<MulBackward0>)

In [69]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [71]:
x.grad == 4 * x

tensor([True, True, True, True])

In [72]:
x.grad.zero_()
y = x.sum()

In [73]:
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [75]:
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

In [76]:
a = torch.randn(size=(), requires_grad=True)

In [77]:
a

tensor(-0.6373, requires_grad=True)

In [78]:
d = f(a)
d.backward()

In [79]:
a.grad

tensor(204800.)

In [80]:
a.grad == d / a

tensor(True)

# Probability